[instrument_catalog]
file = "/home/liuxiang/tmp/bitget_lead_lag_top20_highspeed_20260715T154837Z/inputs/usdt_future_universe.csv"
schema = "aquila.instrument.v1"

[log]
log_level = "info"
file_sink_name = "/home/liuxiang/tmp/bitget_lead_lag_top20_highspeed_20260715T154837Z/logs/bitget_data_fusion.log"
console_sink_name = "bitget_data_session_console"
backend_thread_name = "bitget_data_session_log"
backend_cpu_affinity = 1
format_pattern = "%(log_level_short_code)%(time) %(process_id):%(thread_id) %(file_name):%(caller_function):%(line_number)] %(message)"
timestamp_pattern = "%Y-%m-%d %H:%M:%S.%Qns"

[data_session]
name = "bitget_top20_source"
inst_type = "usdt-futures"
subscribe_symbols = ["BTCUSDT", "SOLUSDT", "DOGEUSDT", "XRPUSDT", "HYPEUSDT", "TACUSDT", "ZECUSDT", "ORDIUSDT", "WLDUSDT", "SLXUSDT", "UBUSDT", "VELVETUSDT", "BTWUSDT", "RAVEUSDT", "SUIUSDT", "AVAXUSDT", "ENAUSDT", "BASUSDT", "HUSDT", "LINKUSDT"]
feeds = ["book_ticker"]

[data_session.websocket.endpoint]
host = "vip-ws-uta-pub-a.bitget.com"
target = "/v3/ws/public/sbe"
enable_tls = true

[data_session.websocket.execution_policy]
bind_cpu_id = 8

[data_shm_sink]
enabled = true
shm_name = "aquila_bgll_bitget_source"
book_ticker_channel_name = "book_ticker_channel"
trade_channel_name = "trade_channel"
create = true
remove_existing = true
