[log]
log_level = "info"
file_sink_name = "/home/liuxiang/log/gate_order_gateway_btc_binance_trigger_gate_quote_probe_20260703.log"
console_sink_name = "gate_order_gateway_btc_binance_trigger_gate_quote_probe_20260703_console"
backend_thread_name = "gate_order_gateway_btc_binance_trigger_gate_quote_probe_20260703_log"
backend_cpu_affinity = 0
format_pattern = "%(log_level_short_code)%(time) %(process_id):%(thread_id) %(file_name):%(caller_function):%(line_number)] %(message)"
timestamp_pattern = "%Y-%m-%d %H:%M:%S.%Qns"

[order_gateway]
name = "gate_order_gateway_btc_binance_trigger_gate_quote_probe_20260703"
shm_name = "aquila_ogw_btc_binance_trigger_probe_20260703"
route_count = 2
command_queue_capacity = 4096
event_queue_capacity = 8192
startup_ready_timeout_s = 30

[[order_gateway.routes]]
name = "gtc_route"
order_session_config = "config/order_sessions/gate_order_session_btc_binance_trigger_gate_quote_probe_private_plain_20260703.toml"
worker_cpu_id = 16

[[order_gateway.routes]]
name = "ioc_route"
order_session_config = "config/order_sessions/gate_order_session_btc_binance_trigger_gate_quote_probe_private_plain_20260703.toml"
worker_cpu_id = 17
