#ifndef AQUILA_CORE_COMMON_BOOK_TICKER_FUSION_METADATA_MODE_H_
#define AQUILA_CORE_COMMON_BOOK_TICKER_FUSION_METADATA_MODE_H_

#ifndef AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED
#define AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED 1
#endif

#if AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED < 0 || \
    AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED > 1
#error "AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED must be 0 or 1"
#endif

namespace aquila {

inline constexpr bool kBookTickerFusionMetadataEnabled =
    AQUILA_BOOK_TICKER_FUSION_METADATA_ENABLED != 0;

}  // namespace aquila

#endif  // AQUILA_CORE_COMMON_BOOK_TICKER_FUSION_METADATA_MODE_H_
