[instrument_catalog]
file = "config/instruments/usdt_futures.csv"
schema = "aquila.instrument.v1"

[[data_sessions]]
name = "binance_future_market_data"
type = "BinanceFutureMarketDataSession"
exchange = "binance"
thread = "BinanceMarketDataThread"
enabled = true
websocket.endpoint = { host = "fstream.binance.com" }
websocket.execution_policy = { bind_cpu_id = 3 }
market = "um_futures"
feed = "book_ticker"
symbols = ["BTC_USDT", "ETH_USDT", "SOL_USDT"]
