[log]
log_level = "info"
file_sink_name = "/home/liuxiang/log/binance_data_fusion_trade_4sources.log"
console_sink_name = "binance_data_fusion_trade_4sources_console"
backend_thread_name = "binance_data_fusion_trade_log"
backend_cpu_affinity = 31
format_pattern = "%(log_level_short_code)%(time) %(process_id):%(thread_id) %(file_name):%(caller_function):%(line_number)] %(message)"
timestamp_pattern = "%Y-%m-%d %H:%M:%S.%Qns"

[launch]
name = "binance_data_fusion_trade_4sources"
feed = "trade"
fusion_config = "config/market_data_fusion/binance_trade_fusion_4sources.toml"

[[launch.sources]]
source_id = 0
data_session_config = "config/data_sessions/binance_data_session_30symbols_20260604.toml"
data_session_name = "binance_trade_source_0"
trade_shm_name = "aquila_binance_trade_src_0"
trade_channel_name = "trade_channel"
remove_existing_source_shm = true
bind_cpu_id = 17

[[launch.sources]]
source_id = 1
data_session_config = "config/data_sessions/binance_data_session_30symbols_20260604.toml"
data_session_name = "binance_trade_source_1"
trade_shm_name = "aquila_binance_trade_src_1"
trade_channel_name = "trade_channel"
remove_existing_source_shm = true
bind_cpu_id = 18

[[launch.sources]]
source_id = 2
data_session_config = "config/data_sessions/binance_data_session_30symbols_20260604.toml"
data_session_name = "binance_trade_source_2"
trade_shm_name = "aquila_binance_trade_src_2"
trade_channel_name = "trade_channel"
remove_existing_source_shm = true
bind_cpu_id = 19

[[launch.sources]]
source_id = 3
data_session_config = "config/data_sessions/binance_data_session_30symbols_20260604.toml"
data_session_name = "binance_trade_source_3"
trade_shm_name = "aquila_binance_trade_src_3"
trade_channel_name = "trade_channel"
remove_existing_source_shm = true
bind_cpu_id = 20
