[fusion]
name = "gate_book_ticker_fusion_30symbols_20260627_4sources"
max_events_per_source = 1
bind_cpu_id = 2
max_symbol_id = 4096

[fusion.output]
shm_name = "aquila_gate_book_ticker_fusion_30symbols_20260627"
channel_name = "book_ticker_channel"
remove_existing = true
metadata_bin = "/home/liuxiang/tmp/lead_lag_fusion_live_30symbols_20260627/gate/fusion_metadata.bin"

[[fusion.sources]]
source_id = 0
name = "gate_source_0_30symbols_20260627"
shm_name = "aquila_gate_btf_30s_20260627_src_0"
channel_name = "book_ticker_channel"

[[fusion.sources]]
source_id = 1
name = "gate_source_1_30symbols_20260627"
shm_name = "aquila_gate_btf_30s_20260627_src_1"
channel_name = "book_ticker_channel"

[[fusion.sources]]
source_id = 2
name = "gate_source_2_30symbols_20260627"
shm_name = "aquila_gate_btf_30s_20260627_src_2"
channel_name = "book_ticker_channel"

[[fusion.sources]]
source_id = 3
name = "gate_source_3_30symbols_20260627"
shm_name = "aquila_gate_btf_30s_20260627_src_3"
channel_name = "book_ticker_channel"
