[instrument_catalog]
file = "config/instruments/usdt_futures_common_gate_binance_20260602.csv"
schema = "aquila.instrument.v1"

[log]
log_level = "info"
file_sink_name = "/home/liuxiang/log/binance_book_ticker_fusion_source0_recorder.log"
console_sink_name = "binance_book_ticker_fusion_source0_recorder_console"
backend_thread_name = "binance_book_ticker_fusion_source0_recorder_log"
backend_cpu_affinity = 16
format_pattern = "%(log_level_short_code)%(time) %(process_id):%(thread_id) %(file_name):%(caller_function):%(line_number)] %(message)"
timestamp_pattern = "%Y-%m-%d %H:%M:%S.%Qns"

[data_reader]
name = "binance_book_ticker_fusion_source0_recorder"
max_events_per_drain = 1024

[data_reader.execution_policy]
bind_cpu_id = 16
idle_policy = "spin"

[[data_reader.sources]]
name = "binance_source_0"
type = "shm"
exchange = "binance"
feed = "book_ticker"
shm_name = "aquila_binance_book_ticker_src_0"
channel_name = "book_ticker_channel"
start_position = "latest"
read_mode = "drain"
required = true
